- import_playbook: common.yml

- hosts: all
  roles:
    - role: docker-ce
      tags:
        - docker-ce
      become: yes
    - role: shadowsocks-libev
      tags:
        - shadowsocks-libev
      become: yes
