- hosts: all
  roles:
    - role: docker-ce
      tags:
        - docker-ce
      become: yes
    - role: shadowsocks-libev
      tags:
        - shadowsocks-libev
      become: yes
    - { role: common, task: bash, tags: [bash] }
    - { role: common, task: vim, tags: [vim] }
