## ssh task
sshd_config:
  PasswordAuthentication: 'no'
  ChallengeResponseAuthentication: 'no'
  PubkeyAuthentication: 'yes'
# push your private key id_rsa and pubkey id_rsa.pub to remote server
ssh_push_keys: false

## git task
git_config:
  'user.name': Bingzhang Dai
  'user.email': bingzhangdai@outlook.com
  'core.editor': vi

## bash
# if set true, you remote files (e.g. .bashrc) will be cleared
bash_clear_existing: true
shell_plugin:
  fzf:
    install_args: --all

## misc task: soley install these packages
# these packages should be easily installed through package manager
misc_packages:
  - gcc
  - g++
  - python3
  - python3-pip
