## ssh task
sshd_config:
  PasswordAuthentication: 'no'
  ChallengeResponseAuthentication: 'no'
  PubkeyAuthentication: 'yes'
# push private key id_rsa and pubkey id_rsa.pub to remote server
ssh_push_keys: false

## vim plugin manager
vim:
  vundle: false
  plug: true

## git task
git_config:
  'user.name': Bingzhang Dai
  'user.email': bingzhangdai@outlook.com
  'core.editor': vi
  'core.pager': 'less -F -X -R -S -+C'
  'merge.log': 'true'
  'alias.last': log -1 HEAD
  # Prune local tracking branches that do not exist on remote anymore
  'alias.aliases': config --get-regexp alias
  'alias.sync': fetch --all --prune
  # Amend the currently staged files to the latest commit
  'alias.amend': 'commit --amend --reuse-message=HEAD'
  # Automatically correct and execute mistyped commands
  'help.autocorrect': '1'

## shell
# if set true, remote files (e.g. .bashrc) will be backed up and cleared, if it is the first time running this task.
shell_clear_existing: true

## misc task: soley install these packages
# these packages should be easily installed through package manager
misc_packages:
  - bash-completion
  - python3
  - python3-pip
