## ssh task
sshd_config:
  PasswordAuthentication: 'no'
  ChallengeResponseAuthentication: 'no'
  PubkeyAuthentication: 'yes'
# push private key id_rsa and pubkey id_rsa.pub to remote server
ssh_push_keys: false

## vim plugin manager
vim:
  vundle: false
  plug: true

## git task
git_config:
  'user.name': Bingzhang Dai
  'user.email': bingzhangdai@outlook.com
  'core.editor': vi

## bash
# if set true, remote files (e.g. .bashrc) will be backed up and cleared
bash_clear_existing: true

## misc task: soley install these packages
# these packages should be easily installed through package manager
misc_packages:
  - gcc
  - g++
  - python3
  - python3-pip
