## ssh task
sshd_config:
  PasswordAuthentication: 'no'
  PubkeyAuthentication: 'yes'
# push your private key id_rsa and pubkey id_rsa.pub to remote server
ssh_push_keys: false

## misc task: soley install these packages
# these packages should be easily installed through package manager
misc_packages:
  - gcc
  - g++
  - python3
  - python3-pip
