ansible_connection: ssh
ansible_port: 22

ansible_user: atl

# workaround: https://github.com/ansible/ansible/issues/24425#issuecomment-437326526
ssh_pass: q1w2E#R$
ansible_ssh_pass: "{{ ssh_pass | string }}"

# Privilege Escalation
# ansible_become: true
# ansible_become_user: root
ansible_become_method: sudo
ansible_become_pass: "{{ ansible_ssh_pass }}"
