- name: install fd for ubuntu
  block:
    - name: install fd through package manager
      apt:
        name: fd-find
        state: latest
        update_cache: yes
        cache_valid_time: 86400
      when: ansible_distribution_version is version('19.04', '>=')
    - name: include task for detecting latest fd version
      include_role:
        name: utils
        tasks_from: github-release
      vars:
        user: "{{ fd_github.user }}"
        repo: "{{ fd_github.repo }}"
      when: ansible_distribution_version is version('19.04', '<')
    - name: install latest fd release
      apt:
        deb: "{{ fd_release }}"
      when: ansible_distribution_version is version('19.04', '<')
  become: yes
  when: ansible_distribution == 'Ubuntu'
