- name: make sure git is installed
  import_tasks: misc.yml
  vars:
    packages: ['git']

- name: clone latest junegunn/fzf to ~/.fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ ansible_env.HOME }}/.fzf"
    depth: 1

# install through package manager may not setup key bindings
- name: install fzf through install script
  shell: "{{ ansible_env.HOME }}/.fzf/install {{ shell_plugin.fzf.install_args }}" # noqa 305 301
