- name: install latest git
  package:
    name: git
    state: latest
  become: yes
  tags:
    - packages

# - name: check if git installed and list config
#   command: git config --list
#   register: git_config_list
#   changed_when: false
#   tags:
#     - packages
#     - configuration

# - name: update git global config
#   command: git config --global {{ item.key }} "{{ item.value }}"
#   changed_when: "'='.join([item.key, item.value]) not in git_config_list.stdout_lines"
#   with_dict: "{{ git_config }}"
#   when: git_config is defined
#   tags:
#     - configuration

- name: update git global config
  git_config:
    name: "{{ item.key }}"
    scope: global
    value: "{{ item.value }}"
  with_dict: "{{ git_config }}"
  tags:
    - configuration
