- name: install vim
  package:
    name: vim
    state: present
  become: yes
  tags:
    - packages

# rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(644) [sender=3.1.2]
# Synchronize module doesn't work with vault: https://github.com/ansible/ansible/issues/45161
- name: update .vimrc and vim plugin
  synchronize:
    src: vim/
    dest: "{{ ansible_env.HOME }}"
    recursive: yes
    archive: no
    times: yes
    rsync_opts:
      - "--chmod=Du=rwx,Dog=rx,Fu=rw,Fog=r"
  become: no
  tags:
    - configuration
